const actionTypes = {
  PRODUCT_FETCHED: 'PRODUCT_FETCHED',
  PRODUCT_LOADING: 'PRODUCT_LOADING',
  PRODUCT_FETCH_FAILED: 'PRODUCT_FETCH_FAILED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  ADD_TO_CART: 'ADD_TO_CART',
};

export default actionTypes;
